version: '3.4'

services:
  pis-web-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
        - "5000:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
  client:
    ports:
        - "5001:3000"
  proxy:
    volumes: 
        - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
        - "80:80"