version: '3.4'

services:
  pis-web-api:
    image: ${DOCKER_REGISTRY-}piswebapi
    build:
      context: .
      dockerfile: pis-web-api/Dockerfile

  client:
    image: client
    build: 
        context: ./client
        dockerfile: Dockerfile
    environment:
        - ConnectionDB=${connectionDB}

  proxy:
    image: nginx:mainline